spring.application.name=Arch
server.port = 8081
spring.datasource.url=jdbc:oracle:thin:@192.168.66.50:1521:ccupoms
spring.datasource.username=masadmin
spring.datasource.password=masdev
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
